#!/bin/sh
echo "=== CloudStation Orchestrator Test Entrypoint ==="
echo "Running minimal test without Azure authentication"
echo ""
echo "Environment variables (values masked):"
echo "username=${username:+SET}"
echo "password=${password:+SET}"
echo "tenant=${tenant:+SET}"
echo "NOMAD_META_TASK=$NOMAD_META_TASK"
echo "NOMAD_META_PARAMS length: ${#NOMAD_META_PARAMS}"
echo "REGISTRY_TOKEN=${REGISTRY_TOKEN:+SET}"
echo "ACCESS_TOKEN=${ACCESS_TOKEN:+SET}"
echo "NATS_CLIENT_PRIVATE_KEY=${NATS_CLIENT_PRIVATE_KEY:+SET}"
echo "BACKEND_URL=$BACKEND_URL"
echo "NATS_SERVERS=$NATS_SERVERS"
echo "WS_URL=$WS_URL"
echo ""
echo "Testing cs binary:"
cs --version
echo ""
echo "Testing Docker socket access:"
docker --version
echo ""
echo "Executing command: $@"
exec "$@"
